// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DailyNoteToggleController from "./daily_note_toggle_controller"
application.register("daily-note-toggle", DailyNoteToggleController)

import DiaryEntryController from "./diary_entry_controller"
application.register("diary-entry", DiaryEntryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import analysisChartController from "./analysis_chart_controller.js"
application.register("analysis-chart", analysisChartController)
