FROM ruby:3.3.9-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libjemalloc2 \
    libvips \
    sqlite3 \
    curl \
    nodejs \
    npm \
    libyaml-dev \
    pkg-config && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN npm install -g yarn

RUN gem install foreman

WORKDIR /rails

ENV RAILS_ENV=development
ENV BUNDLE_PATH=/usr/local/bundle

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["bin/dev"]
